### ISSUE TITLE
[test] FunctionPointer testcase defined serial baudrate explicitly

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/core-util#49]
# Description
In test there is an explicit serial port baudrate specified:
* https://github.com/ARMmbed/core-util/blob/master/test/FunctionPointer/main.cpp#L45, see:
```c++
void runTest(void) {
    static Serial pc(USBTX, USBRX);
    pc.baud(115200);
```
# Change required ?
With new configuration merged by Brendan (default baudrate in ```yotta_config```):
* https://github.com/ARMmbed/target-mbed-gcc/pull/20/files (targett.json change)
* https://github.com/ARMmbed/mbed-drivers/pull/128/files (mbed-drivers allign)
# Greentea response
* In Greentea I've implemented yotta_config (for serial port baudrate) response for Brendan's changes: https://github.com/ARMmbed/greentea/pull/41.
* So this baudrate setting can be removed when we merge Greentea.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1377
