### ISSUE TITLE
MBED_UTIL_POOL_ALLOC_DEFAULT_ALIGN definition too small for ARM EABI

### ISSUE THREAD

**Issue by mjs-arm** [ARMmbed/core-util#54]
http://infocenter.arm.com/help/topic/com.arm.doc.ihi0042f/IHI0042F_aapcs.pdf Chapter 4.1 maximum byte alignment of a fundamental type is 8 bytes, therefore MBED_UTIL_POOL_ALLOC_DEFAULT_ALIGN should be defined >= 8

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1756

**Comment by 0xc0170** [comment]
Thanks for reporting.

Code reference: https://github.com/ARMmbed/core-util/blob/master/core-util/PoolAllocator.h#L24
 There is TODO written about this problem, we will look at it
