### ISSUE TITLE
mbed-drivers does not meet specification ~0.11.1 required by core-utils

### ISSUE THREAD

**Issue by kmdewaal** [ARMmbed/core-util#64]
With a "yotta build" of my application I get the following diagnostic:
error: mbed-drivers does not meet specification ~0.11.1 required by core-util
 
The actual version number of the mbed-drivers is 0.12.0.

Note that my application builds correct as far as I can tell.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1933

**Comment by pan-** [comment]
Same here, the build is correct: but the message `error: mbed-drivers does not meet specification ~0.11.1 required by core-util` is displayed everytime. 
It has broke all ble projects builds on Jenkins.

**Comment by 0xc0170** [comment]
Should be fixed with publishing new minor version for core-util.

**Comment by xbodlaender** [comment]
With a "yotta build" of my application I get the following diagnostic:
error: mbed-drivers does not meet specification ~0.12.0 required by mbed-6lowpan-eventloop-adaptor.
the application does not build.

**Comment by 0xc0170** [comment]
@xbodlaender Please share your ``yotta ls`` output. which version of mbed-drivers and core-util are you using. This should not cause the app does not build however.

**Comment by xbodlaender** [comment]
problem solve by update the mbed module. I link the mbed module to my applicaiton. if update from my application, it gives the error message.
