### ISSUE TITLE
Array: Initialisation of internal variables

### ISSUE THREAD

**Issue by adbridge** [ARMmbed/core-util#67]
The following internals should be initialised to sensible defaults (in most cases 0) in the constructor.

_grow_capacity
_alloc_traits
_alignment
_capacity
_elements

**Comment by bogdanm** [comment]
The thing to decide here is if we keep the current double step initialization (constructor+init()) of all the containers in core-util. If we do (which I think is a good idea) we'll have to guard against cases when the user didn't call `init` before attempting an array operation.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2002

**Comment by 0xc0170** [comment]
#73 fixes this, class member initializers were added
