### ISSUE TITLE
Array: push_back on an uninitialised array fails as a side effect

### ISSUE THREAD

**Issue by adbridge** [ARMmbed/core-util#71]
Currently the push_back() code looks like this:

```
   bool push_back(const T& new_element) {
        unsigned idx = _elements, prev_capacity = _capacity;
        if (_elements == _capacity) {
            if (_grow_capacity == 0) { // can we grow?
                return false;
            }
 ```
If this method is called on an uninitialised array then we would expect it to return False, but it does so only as a side effect of trying to test whether the array is allowed to grow.
ie _elements, _capacity and _grow_capacity should all start as 0

It would be safer to have a specific test for the array not having been initialised yet.

**Comment by bogdanm** [comment]
> It would be safer to have a specific test for the array not having been initialised yet.

Absolutely! Although with the kind of changes we're planning `init` might disappear completely, so this might get better all on its own.

**Comment by adbridge** [comment]
We may well have to fix this and the the initialisation of default values asap ready for the Q1 release as the optimisations may not get the go ahead until Q2 ?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2012

**Comment by 0xc0170** [comment]
#73 fixes this
